### ISSUE TITLE
Failed on launch

### ISSUE THREAD

**Issue by margesch** [justinsalamon/audio_to_midi_melodia#13]
What this supossed to mean? It's failed during launch...

D:\audio2midi>python audio_to_midi_melodia.py ~/test.wav ~/test.mid 60 --smooth
0.25 --minduration 0.1 --jams
Traceback (most recent call last):
  File "audio_to_midi_melodia.py", line 3, in <module>
    import librosa
  File "D:\Python27\lib\site-packages\librosa\__init__.py", line 11, in <module>

    from . import cache
  File "D:\Python27\lib\site-packages\librosa\cache.py", line 7, in <module>
    from joblib import Memory
  File "D:\Python27\lib\site-packages\joblib\__init__.py", line 119, in <module>

    from .parallel import Parallel
  File "D:\Python27\lib\site-packages\joblib\parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "D:\Python27\lib\site-packages\joblib\_parallel_backends.py", line 22, in
 <module>
    from .executor import get_memmapping_executor
  File "D:\Python27\lib\site-packages\joblib\executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "D:\Python27\lib\site-packages\joblib\externals\loky\__init__.py", line 1
1, in <module>
    from .backend.context import cpu_count
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\__init__.py"
, line 4, in <module>
    from .context import get_context
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\context.py",
 line 21, in <module>
    from .process import LokyProcess, LokyInitMainProcess
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\process.py",
 line 11, in <module>
    from .compat import BaseProcess
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\compat.py",
line 23, in <module>
    from .compat_win32 import wait
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\compat_win32
.py", line 17, in <module>
    from ._win_wait import wait
  File "D:\Python27\lib\site-packages\joblib\externals\loky\backend\_win_wait.py
", line 26, in <module>
    GetTickCount64 = ctypes.windll.kernel32.GetTickCount64
  File "D:\Python27\lib\ctypes\__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "D:\Python27\lib\ctypes\__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetTickCount64' not found

**Comment by justinsalamon** [comment]
This issue seems to be related to your installation of librosa, rather than this repo. I'll soon be replacing librosa with a lighter library for loading the audio, so this issue might be addressed by this updated. Stay tuned.

**Comment by justinsalamon** [comment]
OK @margesch I just pushed an update (v0.0.3) which doesn't rely on librosa for loading the audio. Please try the latest version and let me know if you still have any issues. Thanks.

**Comment by justinsalamon** [comment]
Stale, closing out.
