### ISSUE TITLE
TypeError: Failed to load plugin: mtg-melodia:melodia

### ISSUE THREAD

**Issue by alexh8555** [justinsalamon/audio_to_midi_melodia#20]
Hi
I have some problem using vamp plug in.
I've read the related issues, however they didn't fix my problem.
I'm using windows 10 64bit and python 3.6.6
It says 

```
Backend TkAgg is interactive backend. Turning interactive mode on.
Vamp::HostExt: Unable to load library "C:\vamp plugins\mtg-melodia.dll"
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "mtg-melodia:melodia"
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c735dc41cd7b>", line 1, in <module>
    runfile('C:/Users/Alex/Desktop/audio_to_midi_melodia-master/test.py', wdir='C:/Users/Alex/Desktop/audio_to_midi_melodia-master')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Alex/Desktop/audio_to_midi_melodia-master/test.py", line 15, in <module>
    data = vamp.collect(audio, sr, "mtg-melodia:melodia")
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\vamp\collect.py", line 166, in collect
    plugin, step_size, block_size = vamp.load.load_and_configure(data, sample_rate, plugin_key, parameters, **kwargs)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\vamp\load.py", line 83, in load_and_configure
    vampyhost.ADAPT_CHANNEL_COUNT)
TypeError: Failed to load plugin: mtg-melodia:melodia
```

I can see the melodia plugin in Sonic Visualiser but it doesn't work in python. Anything else I should try? Thanks.

**Comment by alexh8555** [comment]
Hi
The problem is that I was using python 64 bit version.
After I install 32 bit version it works perfectly!
Here's my working environment
`Windows 10 64-bit` && ` Python 3.7.4 32-bit`
Thanks for your great plugin!

**Comment by justinsalamon** [comment]
Thanks for reporting, I'll update the README to make it clear that python 32-bit is required.
